# Generated by Django 5.0.6 on 2024-08-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0028_alter_profile_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_verified',
            field=models.CharField(choices=[('TO BE APPROVED', 'To be approved'), ('APPROVED', 'Approved'), ('NOT APPROVED', 'Not approved')], default='TO BE APPROVED', max_length=14),
        ),
        migrations.AlterField(
            model_name='profileimage',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
