# Generated by Django 5.0.6 on 2024-08-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0030_alter_profile_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='profileimage',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ethnicity',
            field=models.CharField(choices=[('WHITE', 'White'), ('ASIAN: INDIAN', 'Asian: Indian'), ('ASIAN: PAKISTANI', 'Asian: Pakistani'), ('ASIAN: BANGLADESHI', 'Asian: Bangladeshi'), ('ASIAN: CHINESE', 'Asian: Chinese'), ('BLACK', 'Black'), ('MIXED', 'Mixed'), ('OTHER ETHNICITY', 'Other Ethnicity')], default='BLACK', max_length=100),
        ),
    ]
