<<<<<<< HEAD
import os
import dj_database_url
from channels.layers import get_channel_layer
try:
    import env
except:
    print("Live cannot import env")

if os.environ.get('DEVELOPMENT'):
    development = True
else:
    development =True

USE_TZ = True
=======
"""
Django settings for dating_app project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""
import dj_database_url
import os
import env

>>>>>>> 4efebe4 (Switch from C9 to AWS C9)

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

<<<<<<< HEAD
=======

>>>>>>> 4efebe4 (Switch from C9 to AWS C9)
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
<<<<<<< HEAD
SECRET_KEY = 'django-insecure-hg*$-)srt6=1a6t4+z=scpk%4xgq3nj@apsqxmk*fpej-_2zvz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = development

ALLOWED_HOSTS = ['80b5-105-161-158-190.ngrok-free.app', 'localhost', '127.0.0.1']


# Application definition
=======
SECRET_KEY = os.environ.get('secret_key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [os.environ.get('C9_HOSTNAME'), "5a824725c9bd45ef92e402d580741815.vfs.cloud9.us-east-1.amazonaws.com"]


# Application definition

>>>>>>> 4efebe4 (Switch from C9 to AWS C9)
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
<<<<<<< HEAD
    'django.contrib.sites',
=======
>>>>>>> 4efebe4 (Switch from C9 to AWS C9)
    'django_filters',
    'profiles',
    'chat',
    'home',
    'checkout',
    'account',
    'search',
<<<<<<< HEAD
    'Custom_admin',
    'pass',
    'channels',

    # Remove 'storages' since AWS is not used
=======
    'storages'
>>>>>>> 4efebe4 (Switch from C9 to AWS C9)
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dating_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
<<<<<<< HEAD
                # 'django.template.context_processors.media',
                #'dating_app.context_processors.engagement_processor'
=======
                'django.template.context_processors.media'
>>>>>>> 4efebe4 (Switch from C9 to AWS C9)
            ],
        },
    },
]

WSGI_APPLICATION = 'dating_app.wsgi.application'

<<<<<<< HEAD
try:
    from .local_settings import *
except ImportError:
    pass

# Database
# Uncomment and configure the database settings as per your requirements

# Password validation
=======

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases
    # 'default': dj_database_url.parse("postgres://odrhschsdnqagz:00b639e75d63bd8c3a33b3c033b9882cac171b2aa1a0ef5db4118d35b781539b@ec2-54-228-246-214.eu-west-1.compute.amazonaws.com:5432/ddjkqtuvsjum22")

DATABASES = { 'default' : {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

AWS_S3_OBJECT_PARAMETERS = {
    'Expires': 'Thu, 31 Dec 2099 20:00:00 GMT',
    'CacheControl': 'max-age=94608000'
}

AWS_STORAGE_BUCKET_NAME = 'dating-app-mvd'
AWS_S3_REGION_NAME = 'eu-west-1'
AWS_ACCESS_KEY_ID = os.environ.get("aws_access_key")
AWS_SECRET_ACCESS_KEY = os.environ.get("aws_secret_key")

AWS_S3_CUSTOM_DOMAIN = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

>>>>>>> 4efebe4 (Switch from C9 to AWS C9)
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

<<<<<<< HEAD
# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Africa/Nairobi'
USE_I18N = True
USE_L10N = True
USE_TZ = True


DATE_FORMAT = "d-m-Y"
DATE_INPUT_FORMATS = ['%d/%m/%Y']
USE_L10N = False


MESSAGE_STORAGE = "django.contrib.messages.storage.session.SessionStorage"

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
# Media files (Uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Log in using email
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend', 'profiles.backend.EmailAuth'
]

STRIPE_PUBLISHABLE = os.environ.get('stripe_publishable')
STRIPE_SECRET = os.environ.get('stripe_key')

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379')],
        },
    },
}

CSRF_TRUSTED_ORIGINS = [
    'https://80b5-105-161-158-190.ngrok-free.app'
]
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

ASGI_APPLICATION = 'dating_app.asgi.application'
=======

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/
# Uncomment to host use static files on S3
STATICFILES_LOCATION = 'static'
STATICFILES_STORAGE = 'custom_storages.StaticStorage'

STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)

# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

DATE_INPUT_FORMATS = ['%d/%m/%Y']

MESSAGE_STORAGE = "django.contrib.messages.storage.session.SessionStorage"

MEDIAFILES_LOCATION = 'media'
DEFAULT_FILE_STORAGE = 'custom_storages.MediaStorage'

MEDIA_URL = 'https://%s/%s/' % (AWS_S3_CUSTOM_DOMAIN, MEDIAFILES_LOCATION)
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ** REPLACE os.envrion.get TO os.getenv WHEN env.py FILE IS ADDED **

# Change to a different email address
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587

# Log in using email
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend', 'profiles.backend.EmailAuth']
    
# Make lowercase for AWS Cloud9
STRIPE_PUBLISHABLE = os.environ.get('stripe_publishable')
STRIPE_SECRET = os.environ.get('stripe_key')
>>>>>>> 4efebe4 (Switch from C9 to AWS C9)
