# Generated by Django 3.2.25 on 2024-09-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_auto_20240831_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='signaling_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
