# Generated by Django 5.1 on 2024-09-05 04:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_chatmessage_deleted_for'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='deleted_for',
            field=models.ManyToManyField(blank=True, related_name='deleted_message', to=settings.AUTH_USER_MODEL),
        ),
    ]
