# Generated by Django 5.1 on 2024-09-05 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_chatsession_deleted_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='deleted_for',
        ),
    ]
