# Generated by Django 5.0.6 on 2024-08-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_order_flutterwave_ref_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mpesa_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='plans',
            field=models.CharField(choices=[('plan_F5eyGdYCvZPtON', 'Monthly - $8.99'), ('plan_F5ey2nnZwy5v8Q', '3 Months - $24.99'), ('plan_F5eyNlWXHig7YB', '6 Months - $40.99')], max_length=100),
        ),
    ]
