# Generated by Django 5.0.6 on 2024-08-31 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_order_mpesa_code_alter_order_date_alter_order_plans'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='flutterwave_ref',
            new_name='pesapal_transaction_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='mpesa_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
    ]
