# Generated by Django 3.2.25 on 2024-08-31 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_rename_flutterwave_ref_order_pesapal_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='plans',
            field=models.CharField(choices=[('plan_F5eyGdYCvZPtON', 'Monthly - 250'), ('plan_F5ey2nnZwy5v8Q', '3 Months - 724'), ('plan_F5eyNlWXHig7YB', '6 Months - 1440')], max_length=100),
        ),
    ]
