# Generated by Django 3.2.25 on 2024-09-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0013_auto_20240902_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='plans',
            field=models.CharField(choices=[('plan_F5eyGdYCvZPtON', '1 Month'), ('plan_F5ey2nnZwy5v8Q', '2 Months'), ('plan_F5eyNlWXHig7YB', '3 Months')], max_length=100),
        ),
    ]
